### ISSUE TITLE
Title includes abstract - makes the bibliography strange

### ISSUE THREAD

**Issue by graham-a** [isdata-org/mapping-the-bioeconomy#3]
http://isdata-org.github.io/mapping-the-bioeconomy/TopicModelling2/index.html#/doc/50152

**Comment by graham-a** [comment]
![image](https://cloud.githubusercontent.com/assets/1144704/14888117/f564a30a-0d58-11e6-9366-a8e83a56bb98.png)

**Comment by cbdavis** [comment]
This was due to abstracts appearing in the titles.  Currently fixed by only including titles with <= 500 characters in them.
