### ISSUE TITLE
Add click functionality to the circle?

### ISSUE THREAD

**Issue by graham-a** [isdata-org/mapping-the-bioeconomy#7]
@cbdavis The hover makes it hard to select TAPs/Materials with shorter names.

**Comment by cbdavis** [comment]
Adding a "click to hold" feature might help with this.  In other words, once you click on a name, that selection will stay until you click on a different name.  Now if you can't easily select the shorter name then we would need a different solution.

**Comment by cbdavis** [comment]
I just added this - you click on a name to lock the selection.  You can then click on another name to unlock things.
